/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ChibiLandTestHelperInterface extends Interface {
  getFunction(
    nameOrSignature: "LAND_BASE_PRICE" | "purchase" | "setAllowReceiving"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "LAND_BASE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchase",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowReceiving",
    values: [boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "LAND_BASE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllowReceiving",
    data: BytesLike
  ): Result;
}

export interface ChibiLandTestHelper extends BaseContract {
  connect(runner?: ContractRunner | null): ChibiLandTestHelper;
  waitForDeployment(): Promise<this>;

  interface: ChibiLandTestHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LAND_BASE_PRICE: TypedContractMethod<[], [bigint], "view">;

  purchase: TypedContractMethod<
    [landId: BigNumberish, signature: BytesLike, expiredAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAllowReceiving: TypedContractMethod<
    [value: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LAND_BASE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchase"
  ): TypedContractMethod<
    [landId: BigNumberish, signature: BytesLike, expiredAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowReceiving"
  ): TypedContractMethod<[value: boolean], [void], "nonpayable">;

  filters: {};
}
