/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChibiKingdomRewards } from "./ChibiKingdomRewards";
export type { IClashStaking } from "./IClashStaking";
