/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type TransactionClaimStatusStruct = {
  lockPeriod: BigNumberish;
  status: BigNumberish;
  claimabledAt: BigNumberish;
  unstakedAt: BigNumberish;
};

export type TransactionClaimStatusStructOutput = [
  lockPeriod: bigint,
  status: bigint,
  claimabledAt: bigint,
  unstakedAt: bigint
] & {
  lockPeriod: bigint;
  status: bigint;
  claimabledAt: bigint;
  unstakedAt: bigint;
};

export interface IClashStakingInterface extends Interface {
  getFunction(
    nameOrSignature: "getTransactionClaimStatuses" | "stake"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getTransactionClaimStatuses",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTransactionClaimStatuses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
}

export interface IClashStaking extends BaseContract {
  connect(runner?: ContractRunner | null): IClashStaking;
  waitForDeployment(): Promise<this>;

  interface: IClashStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getTransactionClaimStatuses: TypedContractMethod<
    [transactionIds: BigNumberish[]],
    [TransactionClaimStatusStructOutput[]],
    "view"
  >;

  stake: TypedContractMethod<
    [amount: BigNumberish, lockPeriod: BigNumberish, sender: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getTransactionClaimStatuses"
  ): TypedContractMethod<
    [transactionIds: BigNumberish[]],
    [TransactionClaimStatusStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [amount: BigNumberish, lockPeriod: BigNumberish, sender: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
