/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC1155Burnable,
  IERC1155BurnableInterface,
} from "../../../../contracts/polygon/ChibiTreasureChestOpener.sol/IERC1155Burnable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
    ],
    name: "burnBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC1155Burnable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155BurnableInterface {
    return new Interface(_abi) as IERC1155BurnableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC1155Burnable {
    return new Contract(address, _abi, runner) as unknown as IERC1155Burnable;
  }
}
